### ISSUE TITLE
Server not found

### ISSUE THREAD

**Issue by adammenges** [jupyterlab/jupyterlab_app#146] opened 2018-02-25 03:21 UTC
First off, this is awesome! Thank you guys for all the hard work. Excited to use JupyterLab without accidentally going backwards or any of the other problems that arise from it being browser based. 😄 

I built it using the commands in the readme, it launched and I saw this:

![screen shot 2018-02-24 at 7 15 50 pm](https://user-images.githubusercontent.com/817438/36637717-32efd0fe-1997-11e8-8606-694fc35cc929.png)

`jupyter` is in my path, I launch it with `jupyter lab` often, for instance. I'm probably just missing something.

Thanks again guys.

**Comment by wietsedv** [comment] 2018-02-25 11:55
Duplicate of #138

**Comment by tgeorgeux** [comment] 2018-03-05 19:21
@wietsedv @adammenges I'm going to close this issue, please follow progress on #138 going forward.

**Closed by tgeorgeux** 2018-03-05 19:21 UTC
